### ISSUE TITLE
Allow different credential types under same secret

### ISSUE THREAD

**Issue by jasuarez** [Nitrokey/pynitrokey#430] opened 2023-08-22 07:00 UTC
If I add a let's say Password Safe Credential under Foo secret name, and later add OTP under the same Foo secret name, the Password Safe Credential is lost. And the other way around.

It would be great if we could re-use the same name to store different credential types, like password and otp

**Comment by szszszsz** [comment] 2023-08-22 10:40
This should be possible starting from Nitrokey 3 v1.6.0. See details at:
- https://github.com/Nitrokey/pynitrokey/pull/425

Closing this ticket as a duplicate of https://github.com/Nitrokey/pynitrokey/issues/402.

**Closed by szszszsz** 2023-08-22 10:40 UTC
