### ISSUE TITLE
Problem with using v0.4 package

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#43] opened 2020-09-18 10:41 UTC
After installing the latest `pynitrokey` v0.4, it cannot be called successfully:
```
$ nitropy
AttributeError: module 'pynitrokey' has no attribute 'fido2' 
```

- [ ] correct
- [ ] add CI check
- [ ] check dependencies

**Comment by daringer** [comment] 2020-09-21 09:06
cannot reproduce ;(
```
# to not rely on pip for removal
$ sudo rm -rf /usr/lib/python3.8/pynitrokey* /usr/bin/nitropy
# install
$ sudo pip install pynitrokey
# run
$ nitropy
*** Nitrokey tool for Nitrokey FIDO2 & Nitrokey Start
Usage: nitropy [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  fido2    Interact with Nitrokey FIDO2 keys, see subcommands.
  ls       List Nitrokey keys (in firmware or bootloader mode)
  start    Interact with 'Nitrokey Start' keys, see subcommands.
  version  Version of pynitrokey library and tool.
```

dang, "works on my computer" ... will check CI, or better do a `pip`-based CI

**Comment by daringer** [comment] 2020-09-21 09:31
please check:
https://app.circleci.com/pipelines/github/Nitrokey/pynitrokey/16/workflows/66511b0e-ee25-43ab-aeb6-db2950ed3834/jobs/29

any chance you forgot to use `-U` or something with pip? 
You could also crosscheck the `Makefile` and tell me the difference between your install process and the one CI-ed....

**Comment by szszszsz** [comment] 2020-09-21 10:18
The reproduction scenario is simple call of `pip install` without the `-U`, on a used system, with previously installed `fido2` 0.7.x library.

I believe the problem lies in the requirements file, where `fido2` dependency lowest version is not set:
https://github.com/Nitrokey/pynitrokey/blob/6917b2f412af56e00ebf4b19b1da86381d7c2766/pyproject.toml#L13-L24

**Comment by daringer** [comment] 2020-09-21 10:31
ah ok, good finding, will be fixed in a moment

**Closed** 2020-09-21 10:43 UTC

**Comment by daringer** [comment] 2020-09-21 10:46
added to CI, to not fall over it anytime later:
https://app.circleci.com/pipelines/github/Nitrokey/pynitrokey/18/workflows/f98833c7-503e-48dc-b57d-ff0bcf94c2eb/jobs/36

**Comment by szszszsz** [comment] 2020-09-21 10:54
While at the topic, I would go into more general way of update process check: install the previous version first, then update to latest to see, if all dependencies were set up correctly. That would require locking versions at the time at release though (either `pip freeze` or `pipenv lock`.

**Comment by szszszsz** [comment] 2020-09-24 10:55
Hi!
Could you make a release with that? It breaks CI unless the proper package is pinned.
