### ISSUE TITLE
Extend the Udev diagnostics

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#197] opened 2022-02-10 10:58 UTC
Extend the Udev diagnostics, so that we could recognize from logs directly:
- [ ] if the Udev rules are in place
- [ ] if they are the current version
- [ ] if they are loaded
- [ ] automatic test procedure passes

See below for details:
- https://github.com/Nitrokey/pynitrokey/issues/167#issuecomment-1024921046

Connected:
- https://github.com/Nitrokey/pynitrokey/issues/192

**Comment by robin-nitrokey** [comment] 2022-02-10 12:16
I don’t know if we can and should automate this completely.  My suggestion is to start with a `nitropy check-udev` command that tries to automate as much as possible.  We can test this on multiple systems and use it for debugging.  If it turns out to work reliably and fully automatically, we can execute it by default on connection issues.  Do you agree?

**Comment by szszszsz** [comment] 2022-02-10 12:52
My motivation here is to replace long instructions for the user with an automatic log gathering, thus cutting the debugging/support time. I do not want to automate all, but support us. If it works, great! If not, then we could switch to manual information gathering. No need to test that across systems imho.
I like the command name!

**Comment by robin-nitrokey** [comment] 2022-02-10 15:10
> No need to test that across systems imho.

Not necessarily before we release it, but we should try to check the behavior on different distributions, locales etc.  Some details might be different from system to system.

**Comment by daringer** [comment] 2023-09-05 14:55
This is a duplicate of: https://github.com/Nitrokey/pynitrokey/issues/386 - let's move all udev-rules handling/diagnostics to this issue

**Closed by daringer** 2023-09-05 14:55 UTC
Labels: enhancement, update, device/Nitrokey 3
