### ISSUE TITLE
Missing cryptography extension for fido2 provisioning

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#433] opened 2023-09-07 17:17 UTC
Missing cryptography extension for fido2 provisioning
```
$ pipx run pynitrokey  nk3 provision fido2 --cert data/fido.cert --key data/fido.key
NOTE: running app 'nitropy' from 'pynitrokey'
Command line tool to interact with Nitrokey devices 0.4.39
Critical error:
An unhandled exception occurred
        Exception encountered: ExtensionNotFound("No <class 'cryptography.x509.extensions.BasicConstraints'> extension was found")
```

**Comment by robin-nitrokey** [comment] 2023-09-14 11:21
Can you share the traceback?  I don’t see any place in our code that would cause this exception directly.

**Comment by robin-nitrokey** [comment] 2024-09-24 20:54
Cannot reproduce, closing.  Please re-open with a traceback if the problem appears again.

**Closed by robin-nitrokey** 2024-09-24 20:54 UTC
Labels: device/Nitrokey 3
