### ISSUE TITLE
Evaluate using solo-python as a library instead of forking it

### ISSUE THREAD

**Issue by dvzrv** [Nitrokey/pynitrokey#37] opened 2020-08-17 11:08 UTC
When looking at solo's [documentation](https://docs.solokeys.dev/porting/), it seems that an easier way to do pynitrokey would be to rely on solo as a library.

Is there a specific reason, why a fork was chosen instead? This seems to introduce a lot of overhead in developing this library/application and staying in sync with solo-python.

**Comment by szszszsz** [comment] 2020-08-17 12:02
Hi @dvzrv !

Good spot. You are right - in general there is no need to double the source code. We were evaluating that approach initially and probably will transform to use solo-python as a library in the future, once their API will be properly enhanced (PRs planned; some were sent already I believe). For the initial releases it was faster to fork though, and add our own required features for other products. Some of our FIDO2 extensions may need special treatment though, so we will see how the things go and act accordingly.

**Comment by daringer** [comment] 2020-08-25 22:40
As of now my impression is that it's not even necessary to keep solo-python inside or outside as a dependency:
* `cli.fido2` stuff will be re-written by us anyways
* `fido2` already provides pretty high-lvl functionality, solo-python mainly wraps functionalities from there
  * `client.py` mostly unused, deprecated, unreachable code, most could be thrown away and replaced with `cli.fido2`'s calls to clean up `cli.fido2`
  * `enums.py` + `commands.py` purely command-bytes enums, not fully compatible with nk-fido2, needs adaptations anyways
  * `hmac_secret.py` simple wraps for `fido2.make_credential` and `fido2.challenge_response` 
  * `dfu.py` very dfu-centric, not sure if we want to keep it (partly solo-hacker specific?)
  * `commands.py` -> `fido2 util` implementations likely needed, but lot's of its content is also specific to the solo-hacker

That's mostly it, will check on the way towards v0.5. For now I would tend to remove solo-python as dependency/fork as most functionality is covered by `fido2` directly, further Nitrokey specifics can partly not be introduced into solo-python through the current interface. Let's see if I can confirm this during the path towards v0.5.

**Comment by szszszsz** [comment] 2020-08-26 03:14
Thank you for the analysis. Quick comments:
- `client.py` was initial version of the upstream client, left out of refactoring probably - to remove?
- `dfu.py`: DFU interface is not used by us at all;
- `fido2 util`: these are development functions, used for the build - do you have any specific in mind?

Perhaps it would be better first to merge upstream before refactorization to avoid conflicts.

In general, yes, it's mostly an adapter around `fido2` library, with some custom extensions supported. 
I think the initial question is still valid: can we avoid additional work in porting latest features from upstream, since we could merge/import upstream library instead and perhaps decrease the overhead this way?
What do you think @daringer ?

**Comment by daringer** [comment] 2020-08-26 09:42
haha, yes, ahm no ;) 
There has been a lot of cleanups/refactorization already, but with the idea in mind to take solo-python in as a dependency, so I have anyways on my list to check the solo-python upstream state and if I find useful additions, we should see which way to go.

But if `dfu.py` and `client.py` are not relevant as of now, the overall code-size (as we do not want `cli.fido2` anyways) we would import is really small, anyways one after another, first v0.4 then let's see how this evolves...

**Comment by daringer** [comment] 2023-09-05 11:35
this is clearly an obsolete discussion, solo-python has not been updated for > 3years, closing...

**Closed by daringer** 2023-09-05 11:35 UTC
Labels: question
